### ISSUE TITLE
`WalletStatus` JSON encoding

### ISSUE THREAD

**Issue by kettlebell** [ergoplatform/ergo-node-interface-rust#8]
As part of https://github.com/ergoplatform/oracle-core/issues/42 I found that `WalletStatus` needs the following serde field annotations:

```rust
pub struct WalletStatus {
    #[serde(rename = "isInitialized")]
    pub initialized: bool,
    #[serde(rename = "isUnlocked")]
    pub unlocked: bool,
    #[serde(rename = "changeAddress")]
    pub change_address: Option<P2PKAddressString>,
    #[serde(rename = "walletHeight")]
    pub height: BlockHeight,
    pub error: Option<String>,
}
```

as required by the node (openAPI reference: https://github.com/ergoplatform/ergo/blob/3fa0ed3d73bcc7d1e0130a347b182b8f5313f49e/src/main/resources/api/openapi.yaml#L1511)

I'll just wait for you to merge the `update-ergo-lib-15` branch, then will apply the fix.

**Comment by kettlebell** [comment]
If you don't have any immediate plans for the `update-ergo-lib-15` branch, I'd be happy to refactor this crate as well as `oracle-pool` to depend on `ergo-lib` version 16.

Also when you have time, could you please cut a new minor version for `ergo-lib` to incorporate https://github.com/ergoplatform/sigma-rust/pull/578?

**Comment by greenhat** [comment]
> If you don't have any immediate plans for the `update-ergo-lib-15` branch, I'd be happy to refactor this crate as well as `oracle-pool` to depend on `ergo-lib` version 16.

Please do. I appreciate it!

> Also when you have time, could you please cut a new minor version for `ergo-lib` to incorporate [ergoplatform/sigma-rust#578](https://github.com/ergoplatform/sigma-rust/pull/578)?

Sure, will do. I'd like to include https://github.com/ergoplatform/sigma-rust/pull/577, which I'm wrapping up today.

**Comment by kettlebell** [comment]
> > If you don't have any immediate plans for the `update-ergo-lib-15` branch, I'd be happy to refactor this crate as well as `oracle-pool` to depend on `ergo-lib` version 16.
> 
> Did you have a chance to work on it? If not, I'd be happy to take it back. :) I'm stuck in [ergoplatform/oracle-core#61](https://github.com/ergoplatform/oracle-core/issues/61) on `WalletStatus` parsing.

Oh yes I can get onto it ASAP. https://github.com/ergoplatform/sigma-rust/pull/584 is just about done except for the "task chunking" thing I mentioned in the associated issue. Looks like this is more urgent for now, so can shift to it. Let me know what you think should be prioritised and I'll do it.

**Comment by greenhat** [comment]
I don't want to pull you from way more complex https://github.com/ergoplatform/sigma-rust/pull/584 for this issue. 
I can take care of this if you don't mind.

**Comment by kettlebell** [comment]
Ok sure, no problem. Thanks!
